# Generated by Django 3.2.14 on 2025-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=20)),
                ('series', models.CharField(max_length=10)),
                ('subject', models.CharField(max_length=50)),
                ('sessional1', models.IntegerField(default=0)),
                ('sessional2', models.IntegerField(default=0)),
                ('semester', models.IntegerField(default=0)),
                ('laboratory', models.IntegerField(default=0)),
                ('total_marks', models.FloatField(default=0)),
                ('grade', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
