# Generated by Django 3.2.14 on 2025-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20250909_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentresult',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='grade',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='laboratory',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='register_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='semester',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='series',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='sessional1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='sessional2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='subject',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='total_marks',
            field=models.FloatField(),
        ),
    ]
