# Generated by Django 3.2.14 on 2025-09-09 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20250909_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('s1', models.FloatField(default=0)),
                ('s2', models.FloatField(default=0)),
                ('sem', models.FloatField(default=0)),
                ('lab', models.FloatField(default=0)),
                ('marks', models.FloatField(default=0)),
                ('grade', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('register_number', models.CharField(max_length=50, unique=True)),
                ('series', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='blog.student'),
        ),
    ]
